// Auto generated by build.sh at Thu Jan 23 22:22:52 UTC 2014

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("3.0.1.0")]
[assembly: AssemblyFileVersion("3.0.1.1722")]
[assembly: AssemblyInformationalVersion("See https://github.com/versionone/V1TFS/wiki")]

[assembly: AssemblyProduct("VersionOneTFSServerConfig")]
[assembly: AssemblyTitle("VersionOneTFSServerConfig")]
[assembly: AssemblyDescription("VersionOne Team Foundation Server Integration 2012 Build")]
[assembly: AssemblyCompany("VersionOne, Inc.")]
[assembly: AssemblyCopyright("Copyright 2008-2013, VersionOne, Inc., Licensed under modified BSD.")]

[assembly: AssemblyConfiguration("2012")]
