// Auto generated by build.sh at Fri Apr 12 20:11:53 UTC 2013

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("2.0.2.0")]
[assembly: AssemblyFileVersion("2.0.2.1611")]
[assembly: AssemblyInformationalVersion("See https://github.com/versionone/V1TFS/wiki")]

[assembly: AssemblyProduct("VersionOne.TFS2010.Tests")]
[assembly: AssemblyTitle("VersionOne.TFS2010.Tests")]
[assembly: AssemblyDescription("VersionOne Team Foundation Server Integration Release Build")]
[assembly: AssemblyCompany("VersionOne, Inc.")]
[assembly: AssemblyCopyright("Copyright 2008-2013, VersionOne, Inc., Licensed under modified BSD.")]

[assembly: AssemblyConfiguration("Release")]
